# Generated by Django 3.2.3 on 2021-05-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-tag'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
