# Generated by Django 3.2.3 on 2021-05-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210519_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
